name: build-and-deploy

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 🚀 Deploy
        run: flyctl deploy --image ghcr.io/namtonthat/recipe-converter:latest -a recipe-converter
